### ISSUE TITLE
Ingen entiteter 

### ISSUE THREAD

**Issue by Hoekeren** [fars-fede-fire/clever_api#2]
Efter installationaf integrationen får jeg ingen entiteter. 
Jeg har egen lader og der er en aktiv opladning.

Loggen sigen :
Logger: homeassistant.components.sensor
Source: runner.py:120
Integration: Sensor (documentation, issues)
First occurred: 18.16.53 (3 occurrences)
Last logged: 18.17.22

Setup of sensor platform clever_api is taking over 10 seconds.
Setup of sensor platform energidataservice is taking over 10 seconds.
Setup of sensor platform dreame_vacuum is taking over 10 seconds.

**Comment by Hoekeren** [comment]
Der er godt nok blevet oprettet 2 entities, men de er tomme (uden værdier)
![image](https://user-images.githubusercontent.com/33251946/213930815-38d5e3cf-59cb-42c2-b947-10fb74934775.png)

**Comment by Hoekeren** [comment]
Denne fejl stammer fra en brugerdefineret integration.

Logger: aiohttp.server
Source: custom_components/clever_api/login/__init__.py:24
Integration: Clever API (documentation, issues)
First occurred: 18.28.20 (1 occurrences)
Last logged: 18.28.20

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/clever_api/config_flow.py", line 101, in async_step_url
    api_key = await obtain_api_key(user_input, self.hass)
  File "/config/custom_components/clever_api/config_flow.py", line 46, in obtain_api_key
    api_key = await login.exchange_secretCode(data["url"])
  File "/config/custom_components/clever_api/login/__init__.py", line 24, in exchange_secretCode
    secret_code = url.split("secretCode=")[1]
IndexError: list index out of range

**Comment by fars-fede-fire** [comment]
Har dine entiteter nogen attributer?

**Comment by Hoekeren** [comment]
Med venlig hilsenChristianFra: fars-fede-fire ***@***.***>Sendt: søndag den 22. januar 2023 19.20Til: fars-fede-fire/clever_api ***@***.***>Cc: Hoekeren ***@***.***>; Author ***@***.***>Emne: Re: [fars-fede-fire/clever_api] Ingen entiteter (Issue #2)
Har dine entiteter nogen attributer?

**Comment by Hoekeren** [comment]
Efter seneste opdatering, har jeg nu 3 entities. De er alle aktive og opdateres når jeg lader👍
